defmodule VostokServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :vostok_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_vostok_server_key",
    signing_salt: "i7DXyXg3",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]
  socket "/socket/device", VostokServerWeb.DeviceSocket,
    websocket: [serializer: [{Phoenix.Socket.V2.JSONSerializer, "~> 2.0.0"}, {Phoenix.Socket.V1.JSONSerializer, "~> 1.0.0"}]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :vostok_server,
    gzip: not code_reloading?,
    only: VostokServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :vostok_server
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug VostokServerWeb.Plugs.SecurityHeaders
  plug Plug.Session, @session_options
  plug VostokServerWeb.Router
end
